create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  date text not null,
  amount double precision not null,
  type text not null check (type in ('income', 'expense', 'transfer')),
  category text not null default '',
  subcategory text not null default '',
  asset text not null default '',
  counter_asset text not null default '',
  memo text not null default '',
  tag text not null default '',
  balance double precision,
  merchant text not null default '',
  source_file text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.import_files (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  source_file text not null,
  transaction_count integer not null default 0,
  first_date text not null default '',
  last_date text not null default '',
  uploaded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source_file)
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  parent_name text not null default '',
  type text not null default 'mixed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name, parent_name)
);

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  kind text not null default 'other',
  initial_value double precision not null default 0,
  is_hidden boolean not null default false,
  is_archived boolean not null default false,
  linked_asset text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.settings (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key text not null,
  value text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

create table if not exists public.manual_net_worth (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  period text not null check (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  amount double precision not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, period)
);

create index if not exists idx_transactions_user_date on public.transactions(user_id, date desc);
create index if not exists idx_transactions_user_type on public.transactions(user_id, type);
create index if not exists idx_transactions_user_category on public.transactions(user_id, category);
create index if not exists idx_transactions_user_asset on public.transactions(user_id, asset);
create index if not exists idx_transactions_user_source on public.transactions(user_id, source_file);

alter table public.transactions enable row level security;
alter table public.import_files enable row level security;
alter table public.categories enable row level security;
alter table public.assets enable row level security;
alter table public.tags enable row level security;
alter table public.settings enable row level security;
alter table public.manual_net_worth enable row level security;

drop policy if exists "own transactions" on public.transactions;
create policy "own transactions" on public.transactions for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "own import files" on public.import_files;
create policy "own import files" on public.import_files for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "own categories" on public.categories;
create policy "own categories" on public.categories for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "own assets" on public.assets;
create policy "own assets" on public.assets for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "own tags" on public.tags;
create policy "own tags" on public.tags for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "own settings" on public.settings;
create policy "own settings" on public.settings for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "own manual net worth" on public.manual_net_worth;
create policy "own manual net worth" on public.manual_net_worth for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
